#!/bin/bash
# Claude Code Multi-Provider Switcher - Automatic Installer
#
# 🔒 Security-conscious? Review this script or use manual installation:
#    https://github.com/FlorianBruniaux/cc-copilot-bridge/blob/main/QUICKSTART.md#option-2-manual-security-conscious---3-minutes
#
# Usage: curl -fsSL https://raw.githubusercontent.com/FlorianBruniaux/cc-copilot-bridge/main/install.sh | bash

set -e

# Colors
BLUE='\033[0;34m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}"
cat << 'EOF'
   _____ _                 _         _____          _ _       _
  / ____| |               | |       / ____|        (_) |     | |
 | |    | | __ _ _   _  __| | ___  | (_____      ___| |_ ___| |__
 | |    | |/ _` | | | |/ _` |/ _ \  \___ \ \ /\ / / | __/ __| '_ \
 | |____| | (_| | |_| | (_| |  __/  ____) \ V  V /| | || (__| | | |
  \_____|_|\__,_|\__,_|\__,_|\___| |_____/ \_/\_/ |_|\__\___|_| |_|

EOF
echo -e "${NC}"
echo "Claude Code Multi-Provider Switcher Installer"
echo "=============================================="
echo ""
echo -e "${GREEN}✓ Respects your shell config${NC}"
echo "  This installer will:"
echo "    - Download claude-switch to ~/bin/"
echo "    - Create ~/.claude/aliases.sh"
echo "    - ASK before modifying your .zshrc/.bashrc"
echo ""

# Detect OS
OS="$(uname -s)"
case "$OS" in
    Darwin*)
        SHELL_RC="$HOME/.zshrc"
        echo "✓ Detected: macOS"
        ;;
    Linux*)
        if [ -f "$HOME/.zshrc" ]; then
            SHELL_RC="$HOME/.zshrc"
            echo "✓ Detected: Linux (zsh)"
        else
            SHELL_RC="$HOME/.bashrc"
            echo "✓ Detected: Linux (bash)"
        fi
        ;;
    *)
        echo -e "${RED}✗ Unsupported OS: $OS${NC}"
        exit 1
        ;;
esac

echo ""

# Check prerequisites
echo "Checking prerequisites..."
echo ""

# Check Claude Code
if ! command -v claude &> /dev/null; then
    echo -e "${ORANGE}⚠ Claude Code CLI not found${NC}"
    echo "  Install it with: npm install -g @anthropic-ai/claude-code"
    echo ""
else
    echo -e "${GREEN}✓ Claude Code CLI installed${NC}"
fi

# Check nc (netcat)
if ! command -v nc &> /dev/null; then
    echo -e "${ORANGE}⚠ netcat (nc) not found${NC}"
    echo "  Install it with: brew install netcat (macOS) or apt-get install netcat (Linux)"
    echo ""
else
    echo -e "${GREEN}✓ netcat installed${NC}"
fi

echo ""

# Create ~/bin if it doesn't exist
if [ ! -d "$HOME/bin" ]; then
    mkdir -p "$HOME/bin"
    echo "✓ Created ~/bin directory"
fi

# Download claude-switch script
echo "Downloading claude-switch script..."
SCRIPT_URL="https://raw.githubusercontent.com/FlorianBruniaux/cc-copilot-bridge/main/claude-switch"
SCRIPT_PATH="$HOME/bin/claude-switch"

# For local testing, use the current directory
if [ -f "./claude-switch" ]; then
    cp ./claude-switch "$SCRIPT_PATH"
    echo "✓ Copied local claude-switch to ~/bin/"
else
    if command -v curl &> /dev/null; then
        curl -fsSL "$SCRIPT_URL" -o "$SCRIPT_PATH" 2>/dev/null || {
            echo -e "${RED}✗ Failed to download script${NC}"
            echo "  Make sure you have internet connection"
            exit 1
        }
    elif command -v wget &> /dev/null; then
        wget -q "$SCRIPT_URL" -O "$SCRIPT_PATH" || {
            echo -e "${RED}✗ Failed to download script${NC}"
            exit 1
        }
    else
        echo -e "${RED}✗ curl or wget required${NC}"
        exit 1
    fi
    echo "✓ Downloaded claude-switch"
fi

# Make executable
chmod +x "$SCRIPT_PATH"
echo "✓ Made claude-switch executable"

# Generate aliases file
echo ""
echo "Configuring shell aliases..."

ALIASES_FILE="$HOME/.claude/aliases.sh"

cat > "$ALIASES_FILE" << 'ALIASES_EOF'
# Claude Code Multi-Provider Aliases
# Generated by claude-switch installer

export PATH="$HOME/bin:$PATH"

# Core Commands
alias ccd='claude-switch direct'
alias ccc='claude-switch copilot'
alias cco='claude-switch ollama'
alias ccs='claude-switch status'

# Copilot Model Shortcuts
alias ccc-opus='COPILOT_MODEL=claude-opus-4.5 claude-switch copilot'
alias ccc-sonnet='COPILOT_MODEL=claude-sonnet-4.5 claude-switch copilot'
alias ccc-haiku='COPILOT_MODEL=claude-haiku-4.5 claude-switch copilot'
alias ccc-gpt='COPILOT_MODEL=gpt-4.1 claude-switch copilot'
alias ccc-gemini='COPILOT_MODEL=gemini-2.5-pro claude-switch copilot'
alias ccc-gemini3='COPILOT_MODEL=gemini-3-flash-preview claude-switch copilot'
alias ccc-gemini3-pro='COPILOT_MODEL=gemini-3-pro-preview claude-switch copilot'

# Ollama Model Shortcuts
alias cco-devstral='OLLAMA_MODEL=devstral-small-2 claude-switch ollama'
alias cco-granite='OLLAMA_MODEL=ibm/granite4:small-h claude-switch ollama'
ALIASES_EOF

echo "✓ Created $ALIASES_FILE"

# Ask user if they want automatic configuration
echo ""
echo -e "${BLUE}How would you like to configure aliases?${NC}"
echo ""
echo "1) Auto-add to $SHELL_RC (modify shell config)"
echo "2) Manual setup (I'll add it myself)"
echo ""
read -p "Choice (1/2, default: 2): " CHOICE
CHOICE=${CHOICE:-2}

if [ "$CHOICE" = "1" ]; then
    if grep -q "source.*\.claude/aliases\.sh" "$SHELL_RC" 2>/dev/null; then
        echo -e "${ORANGE}⚠ Aliases already sourced in $SHELL_RC${NC}"
    else
        echo "" >> "$SHELL_RC"
        echo "# Claude Code Multi-Provider" >> "$SHELL_RC"
        echo "source ~/.claude/aliases.sh" >> "$SHELL_RC"
        echo "✓ Added source line to $SHELL_RC"
    fi
else
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}Manual setup instructions (REQUIRED):${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    echo "Aliases created in: ${GREEN}~/.claude/aliases.sh${NC}"
    echo ""
    echo "You MUST source this file to use the commands (ccd, ccc, cco)."
    echo ""
    echo "Choose one method:"
    echo ""
    echo "1. Standard zsh/bash:"
    echo -e "   ${GREEN}echo 'source ~/.claude/aliases.sh' >> $SHELL_RC${NC}"
    echo ""
    echo "2. Antigen (recommended for managed configs):"
    echo -e "   ${GREEN}Add to .zshrc: antigen bundle ~/.claude/aliases.sh${NC}"
    echo ""
    echo "3. Oh-my-zsh:"
    echo -e "   ${GREEN}ln -s ~/.claude/aliases.sh \$ZSH_CUSTOM/plugins/claude-switch.plugin.zsh${NC}"
    echo -e "   ${GREEN}Add 'claude-switch' to plugins=(...) in .zshrc${NC}"
    echo ""
    echo "4. See all methods: docs/INSTALL-OPTIONS.md"
    echo ""
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
    read -p "Will you configure this manually now? (y/n): " CONFIRM
    CONFIRM=${CONFIRM:-n}

    if [ "$CONFIRM" != "y" ] && [ "$CONFIRM" != "Y" ]; then
        echo ""
        echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo -e "${RED}⚠ WARNING: Installation incomplete!${NC}"
        echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
        echo ""
        echo "claude-switch won't work until you configure aliases."
        echo ""
        echo "To finish setup later:"
        echo -e "  ${BLUE}cat ~/.claude/aliases.sh${NC}  # View aliases"
        echo -e "  ${BLUE}source ~/.claude/aliases.sh${NC}  # Quick test"
        echo ""
        read -p "Press Enter to exit or Ctrl+C to abort installation..."
        echo ""
    else
        echo ""
        echo -e "${GREEN}✓ Great! Remember to source your shell config after adding the line.${NC}"
        echo ""
    fi
fi

# Create .claude directory if it doesn't exist
mkdir -p "$HOME/.claude"

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ Installation complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Next steps:"
echo ""

if [ "$CHOICE" = "1" ]; then
    echo "1. Reload your shell configuration:"
    echo -e "   ${BLUE}source $SHELL_RC${NC}"
    echo ""
else
    echo "1. Add aliases to your shell config (IMPORTANT):"
    echo ""
    echo "   Standard zsh/bash:"
    echo -e "     ${BLUE}echo 'source ~/.claude/aliases.sh' >> $SHELL_RC${NC}"
    echo -e "     ${BLUE}source $SHELL_RC${NC}"
    echo ""
    echo "   With antigen (recommended for managed configs):"
    echo -e "     ${BLUE}Add to .zshrc: antigen bundle ~/.claude/aliases.sh${NC}"
    echo ""
    echo "   With oh-my-zsh:"
    echo -e "     ${BLUE}ln -s ~/.claude/aliases.sh \$ZSH_CUSTOM/plugins/claude-switch.plugin.zsh${NC}"
    echo -e "     ${BLUE}Add 'claude-switch' to plugins=(...) in .zshrc${NC}"
    echo ""
fi
echo "2. Check provider status:"
echo -e "   ${BLUE}ccs${NC}"
echo ""
echo "3. Setup providers (optional):"
echo ""
echo "   📦 GitHub Copilot (free with subscription):"
echo -e "      ${BLUE}npm install -g copilot-api${NC}"
echo -e "      ${BLUE}copilot-api start${NC}"
echo ""
echo "   🔒 Ollama (local, private - recommended: devstral-small-2):"
echo -e "      ${BLUE}brew install ollama${NC}  # macOS"
echo -e "      ${BLUE}ollama serve${NC}"
echo -e "      ${BLUE}ollama pull devstral-small-2${NC}"
echo ""
echo "   ⚠️  IMPORTANT: Create 64K context Modelfile for Claude Code:"
echo -e "      ${BLUE}mkdir -p ~/.ollama${NC}"
echo -e "      ${BLUE}cat > ~/.ollama/Modelfile.devstral-64k << 'EOF'${NC}"
echo "      FROM devstral-small-2"
echo "      PARAMETER num_ctx 65536"
echo "      PARAMETER temperature 0.15"
echo "      EOF"
echo -e "      ${BLUE}ollama create devstral-64k -f ~/.ollama/Modelfile.devstral-64k${NC}"
echo ""
echo "   📦 Alternative: Pull backup model for long-context tasks:"
echo -e "      ${BLUE}ollama pull ibm/granite4:small-h${NC}"
echo ""
echo "4. Start using:"
echo -e "   ${BLUE}ccd${NC}        # Anthropic Direct"
echo -e "   ${BLUE}ccc${NC}        # GitHub Copilot"
echo -e "   ${BLUE}cco${NC}        # Ollama Local"
echo -e "   ${BLUE}ccc-opus${NC}   # Copilot with Opus model"
echo ""
echo "Documentation:"
echo "  https://github.com/FlorianBruniaux/cc-copilot-bridge"
echo ""
echo -e "${ORANGE}⚠ Don't forget to: source $SHELL_RC${NC}"
echo ""
